# Generated by Django 4.2.13 on 2025-08-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telemetry',
            new_name='devices_tel_timesta_bd8d1b_idx',
            old_name='devices_tel_timesta_123abc',
        ),
    ]
