# Generated by Django 4.2.13 on 2025-08-20 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_rename_devices_tel_timesta_123abc_devices_tel_timesta_bd8d1b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(help_text="Unique identifier for the device model (e.g., 'sensor_temp_v1')", max_length=128, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for the device model', max_length=128)),
                ('version', models.CharField(blank=True, help_text="Version of the device model (e.g., '1.0.0')", max_length=32)),
                ('schema', models.JSONField(default=dict, help_text='JSON schema defining the structure of telemetry data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Model Definition',
                'verbose_name_plural': 'Device Model Definitions',
                'ordering': ['name', 'version'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['gateway__name', 'name', 'device_id'], 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='gateway',
            options={'ordering': ['-last_seen', 'name'], 'verbose_name': 'Gateway', 'verbose_name_plural': 'Gateways'},
        ),
        migrations.AlterModelOptions(
            name='telemetry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Telemetry', 'verbose_name_plural': 'Telemetry'},
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='last_telemetry',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last received telemetry data', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gateway',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this gateway is active and should receive commands'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Unique identifier for the device within its gateway', max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='gateway',
            field=models.ForeignKey(help_text='Gateway that manages this device', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.gateway'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Whether the device is currently online'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, help_text='Device model/part number', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable name for the device', max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('sensor', 'Sensor'), ('actuator', 'Actuator'), ('camera', 'Camera'), ('relay', 'Relay'), ('dimmer', 'Dimmer'), ('switch', 'Switch')], default='sensor', help_text='Type of device (sensor, actuator, camera, etc.)', max_length=64),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gateway_id',
            field=models.CharField(help_text='Unique identifier for the gateway (usually MAC address or serial number)', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this gateway was seen online', null=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='name',
            field=models.CharField(blank=True, help_text='Human-readable name for the gateway', max_length=128),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='owner',
            field=models.ForeignKey(help_text='User who owns this gateway', on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='device',
            field=models.ForeignKey(help_text='Device that generated this telemetry data', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='payload',
            field=models.JSONField(help_text='The actual telemetry data as JSON'),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this telemetry data was received'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['device', '-timestamp'], name='devices_tel_device__dbeea2_idx'),
        ),
        migrations.AddField(
            model_name='device',
            name='model_definition',
            field=models.ForeignKey(blank=True, help_text='Reference to device model definition for validation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicemodeldefinition'),
        ),
    ]
