# Generated by Django 4.2.13 on 2025-08-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_model_registry'),
    ]

    operations = [
    ]
